# -*- coding: utf-8 -*-
"""reading_posterior_samples_tutorial.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/github/ColmTalbot/Bilby-GWTC-1-Analysis-and-Verification/blob/master/tutorials/reading_posterior_samples_tutorial.ipynb

# Reading and plotting `bilby` posterior samples

In this tutorial, we will read `bilby` posterior samples for one of the gravitational-wave events contained within this repository. We're going to show GW170729 as an example, but this tutorial will work for any of the events. We will demonstrate the reading of each kind of results file provided.

### Import required packages
"""

# Commented out IPython magic to ensure Python compatibility.
import numpy as np
import bilby
import matplotlib.pyplot as plt
# %matplotlib inline

"""### A useful plotting function
We'll need this later.
"""

def plot_data(data, density, bins, histtype, alpha, xlabel, ylabel, title, label='posterior'):
    fig = plt.figure()
    plt.hist(data, density=density, bins=bins, histtype=histtype, alpha=alpha, label=label)
    plt.xlabel(xlabel)
    plt.ylabel(ylabel)
    plt.title(title)
    plt.legend()
    plt.show()

"""## Example 1: Reading `.dat`
This kind of file contains only the posterior samples for the event.

First, we need to read in the data file. For this, you will need to [download the posterior samples](https://dcc.ligo.org/LIGO-P2000193).
"""

data_file = "../gwtc-1_analysis_results/downsampled_posterior_samples/GW170729_downsampled_posterior_samples.dat"
bilby_posterior_samples = np.genfromtxt(data_file, names=True)

"""We can print the names of all the data fields contained in the file."""

bilby_posterior_samples.dtype

"""Let's plot one of the bilary parameters. We'll choose the chirp mass as an example."""

data = bilby_posterior_samples['chirp_mass']

"""The cell below defines how we want the plot to look."""

xlabel = "chirp mass [M_sun]"
ylabel = "posterior probability"
title = "chirp mass for GW170729"
bins = 30
density = True
histtype = "stepfilled"
alpha = 0.5

"""Now we can plot the data using the function we defined earlier."""

plot_data(data, density, bins, histtype, alpha, xlabel, ylabel, title)

"""## Example 2: Reading `.json`
This kind of file contains lots of different data about the analysis. It includes information about the priors and the parameters that were sampled in, as well as the posterior samples.

Again, the first step is to read in the data file. For this, you will need to [download the bilby results files](https://dcc.ligo.org/LIGO-P2000193). We can read it directly into a bilby result object.
"""

data_file = "../gwtc-1_analysis_results/bilby_result_files/GW170729_result_file.json"
bilby_result = bilby.gw.result.CBCResult.from_json(data_file)

"""We can extract the data that we want from the result object's saved posterior samples."""

data = bilby_result.posterior['chirp_mass']

"""Again, we can plot this using the function we defined earlier."""

plot_data(data, density, bins, histtype, alpha, xlabel, ylabel, title, file_extension='json')

"""As well as the posterior samples, the `result` object contains lots of useful information about the way the analysis was run, like the kinds of priors we used. Let's have a look at the prior we set on chirp mass. First, we recover the bilby `Prior` object for chirp mass."""

prior_object = bilby_result.priors['chirp_mass']

"""Then we take some samples from it."""

prior_samples = prior_object.sample(1000)

"""We can plot the posterior and the prior on the same plot, again using the function we defined earlier."""

data = [data, prior_samples]
legend = ['posterior', 'prior']
file_extension = 'json_plus_prior'
plot_data(data, density, bins, histtype, alpha, xlabel, ylabel, title, file_extension)

